refactor

diff --git a/.github/workflows/sync.yml b/.github/workflows/sync.yml
--- a/.github/workflows/sync.yml
+++ b/.github/workflows/sync.yml
@@ -20,9 +20,12 @@ jobs:
         git config --global user.name '${{ github.actor }}'
         git config --global user.email '${{ github.actor }}@users.noreply.github.com'
         git fetch
-        git merge -s recursive -X ours origin/main
-        git status | grep -P 'deleted by us|added by them' | awk '{print $4}' | xargs git rm || echo "no files changed."
+        git merge -s recursive -X ours origin/main || echo "merge failed (no branch?)"
+        git status | grep -P 'deleted by us|added by them' | awk '{print $4}' | xargs git rm || echo fine
+        local previous=$(cat .github/assets/remote.txt | cut -d/ -f4-5)
         echo "$(git remote get-url origin)" > .github/assets/remote.txt
+        local updated=$(cat .github/assets/remote.txt | cut -d/ -f4-5)
+        find README.md .github/ -type f |  xargs sed -i "s@$previous@$updated@g"
         git add --all
         git commit -am "♻️" || echo "resolved"
         git push
